//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerNews.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int Id { get; set; }
        public int Id_Version { get; set; }
        public string Titulo { get; set; }
        public string Contenido { get; set; }
        public int Idioma { get; set; }
        public int Seccion { get; set; }
        public Nullable<int> Seccion_detalle { get; set; }
        public string Edicion { get; set; }
        public string Top_new { get; set; }
        public string Visible { get; set; }
        public string Destacada { get; set; }
        public string Editorial { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Nullable<System.DateTime> fecha_editado { get; set; }
        public Nullable<int> creador { get; set; }
    }
}
