//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerNews.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datos_usuario
    {
        public int Id { get; set; }
        public string usuario { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> ultima_conexion { get; set; }
    }
}
