//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnerNews.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Edicion
    {
        public int Id_Version { get; set; }
        public int Id_Toque { get; set; }
        public string Articulos { get; set; }
        public int Id_Edicion { get; set; }
        public Nullable<int> Idioma { get; set; }
    }
}
